### ISSUE TITLE
Fails with FOC/Crud Plugin

### ISSUE THREAD

**Issue by justinatack** [UseMuffin/Obfuscate#4]
I'm using the FOC/Crud plugin and would like to use this as well but it seems to conflict. Is there something I can do to make this work?

```
2016-01-23 05:02:46 Error: [Cake\Network\Exception\NotFoundException] Not found
Request URL: /en/users/view/1
Stack Trace:
#0 /home/vagrant/public/cakebooks/vendor/friendsofcake/crud/src/Traits/FindMethodTrait.php(50): Crud\Action\ViewAction->_notFound('1', Object(Crud\Event\Subject))
#1 /home/vagrant/public/cakebooks/vendor/friendsofcake/crud/src/Action/viewAction.php(53): Crud\Action\ViewAction->_findRecord('1', Object(Crud\Event\Subject))
#2 [internal function]: Crud\Action\ViewAction->_handle('1')
#3 /home/vagrant/public/cakebooks/vendor/friendsofcake/crud/src/Action/BaseAction.php(69): call_user_func_array(Array, Array)
#4 /home/vagrant/public/cakebooks/vendor/friendsofcake/crud/src/Controller/Component/CrudComponent.php(228): Crud\Action\BaseAction->handle(Array)
#5 /home/vagrant/public/cakebooks/src/Controller/UsersController.php(133): Crud\Controller\Component\CrudComponent->execute()
#6 [internal function]: App\Controller\UsersController->view('1')
#7 /home/vagrant/public/cakebooks/vendor/friendsofcake/crud/src/Controller/ControllerTrait.php(51): call_user_func_array(Array, Array)
#8 /home/vagrant/public/cakebooks/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): App\Controller\AppController->invokeAction()
#9 /home/vagrant/public/cakebooks/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#10 /home/vagrant/public/cakebooks/webroot/index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#11 {main}
```

I guess this is more a CRUD issue but I thought you might have some ideas.

**Comment by ADmad** [comment]
You need to set the `findMethod` config for view action to `obfuscate`.

**Comment by ADmad** [comment]
@bravo-kernel Would be great if you could help updating the docs for using the plugin with CRUD :)

**Comment by justinatack** [comment]
Not sure if this is what you mean? I set the findMethod in my view action to the following

```
$this->Crud->action()->findMethod('obfuscate');
```

but I get 

```
Unknown finder method "obfuscate"
```

So it would seem that I have to create my own findMethod as well?

**Comment by bravo-kernel** [comment]
This works for me: 

``` php
    public function index()
    {
        $this->Crud->action()->config('findMethod', 'obfuscated');
        return $this->Crud->execute();
    }
```

``` php
    public function view()
    {
        $this->Crud->action()->config('findMethod', 'obfuscated');
        return $this->Crud->execute();
    }
```

**Comment by bravo-kernel** [comment]
Updated and tested the code above, should work

**Comment by ADmad** [comment]
@justinatack You need to load the Obfuscate behavior for your table.

**Comment by bravo-kernel** [comment]
For historic purposes... @justinatack missed the trailing `d` in `obfuscated` in his example. Should be (and will also work):

``` php
$this->Crud->action()->findMethod('obfuscated');
```

**Comment by ADmad** [comment]
Ah, I mistyped the name in my initial comment.

**Comment by bravo-kernel** [comment]
@justinatack can this issue be closed?

**Comment by justinatack** [comment]
@bravo-kernel Yeah you can close it. I found it did improve things a little with my view, add and edit views but I was still having issues with my index view and form submissions, I think it's related to something I have done. I have put this issue aside for now as I don't have time to address it but I'll look at it again in the near future. Thanks for all the help.
